version: '3.8'
services:
  company-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/pajovicv/companyandreservationservices:latest
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      # Explicitly forward only what the app uses (values come from .env)
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MINIO_SECRETE_KEY: ${MINIO_SECRETE_KEY}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PUBLIC_BUCKET: ${MINIO_PUBLIC_BUCKET}
      SMS_API_KEY: ${SMS_API_KEY}
      EMPLOYEE_SERVICE_URL: ${EMPLOYEE_SERVICE_URL}
      EMPLOYEE_SERVICE_TOKEN: ${EMPLOYEE_SERVICE_TOKEN}
      SERVER_ERROR_INCLUDE_MESSAGE: "always"
      SERVER_ERROR_INCLUDE_STACKTRACE: "ALWAYS"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_SERVLET_MVC_METHOD_ANNOTATION_REQUESTMAPPINGHANDLERMAPPING: DEBUG
      # Optional: log request bodies/headers
      SPRING_MVC_LOG_REQUEST_DETAILS: "true"